version: '3'
services:

  web:
    build: .
    ports:
     - "8000:8000"
    environment:
      RUNMODEL: docker
      ELASTICSEARCH_HOSTS: elasticsearch:9200
      REDIS_HOST: redis:6379
    depends_on:
      - redis
      - elasticsearch
  client:
    image: boyhack/w12scan-client:latest
    environment:
      RUNMODEL: docker
      WEB_INTERFACE: http://web:8000
      REDIS_HOST: redis:6379
    depends_on:
      - web
  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:6.6.0
    ports:
      - "9200:9200"
    restart: always
    expose:
      - "9200"